### ISSUE TITLE
HTML Source

### ISSUE THREAD

**Issue by sdhunt** [morganreed5/prj-rev-bwfs-dasmoto#2]
Your HTML source is reasonably formatted, with correct indentation reflecting the parent/child relationship between elements. 

Consider using whitespace and comments to break up the solid block of code to improve readability. For example: 
```

    <!-- Brushes Section --> 

    <div class="brushes">
        <h2 id="brushes">Brushes</h2>
        <img src="...">
        <h3>Hacksaw Brushes</h3>
        <p>Made of the highest quality... </p>
    </div>

    <!-- Frames Section --> 

    <div class="frames">
        <h2 id="frames">Frames</h2>
        <img src="...">
        <h3>Art Frames (assorted)</h3>
        <p>Assorted frames made of ... </p>
    </div>

    <!-- Paint Section --> 

    <div class="paint">
        <h2 id="paint">Paint</h2>
        <img src="...">
        <h3>Clean Finnish Paint</h3>
        <p>Imported paint from ... </p>
    </div>
```

**Comment by morganreed5** [comment]
I wasn't sure if "overdoing" comments was bad form or at what point whitespace becomes too much, so I was trying to just stick to one space between parent elements. I will definitely add comments and more whitespace going forward, especially as I work on projects that are lengthier and will need maintenance.
